"""Add pitches table

Revision ID: 8efdfa768246
Revises: 33c29348e895
Create Date: 2026-05-30 21:09:23.550631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efdfa768246'
down_revision: Union[str, Sequence[str], None] = '33c29348e895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('style_profile_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_title', sa.String(), nullable=False),
    sa.Column('song_lyrics', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('generated_text', sa.String(), nullable=False),
    sa.Column('user_edited_text', sa.String(), nullable=True),
    sa.Column('final_text', sa.String(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('playlists', 'curator_json',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('playlists', 'contact_revealed_via',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('songs', 'streaming_links',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'streaming_links',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('playlists', 'contact_revealed_via',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('playlists', 'curator_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('pitches')
    # ### end Alembic commands ###
